### PR TITLE
tqdm for the fixed odeint loop

### PR DESCRIPTION
**Pull request by joglekara**

### CODE REVIEW

**Comment by joglekara** [comment]
Probably need a way to suppress it or provide a flag for usage because the NN usecase is such that this would be unnecessary at best and cumbersome at worst

**Comment by Zymrael** [comment]
I agree that this is unnecessary (and adds a small overhead). What would be a use case for this? Logging step times and other metrics via a proper Solution class should cover most use cases I can think of.

**Comment by joglekara** [comment]
A use case might be a long time-scale PDE solve, ~10^5 steps, 0.2-0.5s per step.

**Comment by Zymrael** [comment]
this calls for a `verbose` option perhaps.

**Pull request closed without merging**
