### PR TITLE
save at for fixed odeint

### PR DESCRIPTION
**Pull request by joglekara**

### CODE REVIEW

**Comment by Zymrael** [comment]
Looks good, can we add a small test for this?

**Review by massastrello — COMMENTED** [review]
I checked the code and tried a minimal example

```
import torch
from torchdyn.numerics import odeint
def f(t, x):
    return -x
t_span = torch.linspace(0, 1, 11)
x0 = torch.randn(1, 2)
t_save = torch.tensor([.5, .75])
t, x = odeint(f, x0, t_span, t_save=t_save, solver='rk4')
```
I have a couple of comments:
* `t_store` is initialized as `t_store=[t]`. However in this way `t_store` will always contain `t_span[0]` (the same applied to `sol` in this context).
* In fixed-step solvers your implementation would be useful only if `t_store` is a subset of `t_span`. I think we should check whether at least some elements of `t_store` are present in `t_span` before integrating the ODE. On the other hand, if this is the goal, a simpler and more efficient way of selecting a subset of the solution according to `t_save` would be
  ```
    t, x = odeint(f, x0, t_span, solver='rk4')
    idx = torch.isclose(t_save, t_span)
    t, x = t_span[idx], x[idx]
  ```
  so that we can avoid running through the  `if torch.isclose(t, t_save).sum():` condition at each solver's step.

**Comment by joglekara** [comment]
@massastrello on second thought, the indexing approach doesn't help here because the goal is to no longer store the full state along the integration path. For motivation, the state of some PDE solves relevant to plasma physics can be O(GB).

The way I see it, there are two sides to the spectrum

1) where `solver.step()` can be expensive and `x` can be very large. In those situations, it is not expensive to run the `if` call within the loop
2) where `solver.step()` is cheap and `x` is small in which case we can process the stored quantities after the loop

I'm inclined to think the `if` + `sum()` call may not be so expensive anyway because `t_span` is at worst still a 1D quantity but curious to hear what you think

**Comment by Zymrael** [comment]
@massastrello point is that regardless of how we check `t_span` vs `t_store`, the latter should always be in fixed-step solvers a strict subset of the first; basically a config for checkpoints. However, I don't think `allclose` makes a bit difference since as you mentioned `t_span` is a 1D array. 

For adaptive-steppers, interpolation allows us to save at "arbitrary" times. In those cases, `allclose` checks are definitely required.

**Review by massastrello — CHANGES_REQUESTED** [review]
I checked your additional changes. There are still a couple of things I would like to discuss before merge:

* For personal flavor I would prefer to change `t_save` to `save_at`. It seems more intuitive in the API.
* I think we should check whether `save_at` is a subset of `t_span` with an `assert`, e.g.
`assert torch.isin(save_at, t_span), "each element of save_at [torch.Tensor] must be contained in t_span [torch.Tensor]"`
* If the condition is satisfied then `t_store` will always be equal to `save_at` and we don't need to construct it on the fly during the solver's loop.
* Regardless, there's a mistake at line 416 of `odeint.py`
`if torch.isclose(torch.Tensor([0.0]), t_save).sum():` should be `if torch.isclose(torch.Tensor(t_span[0]), t_save).sum():`

**Comment by joglekara** [comment]
done

**Comment by massastrello** [comment]
Thanks! Looks good to me.

**Pull request merged**
