### PR TITLE
Torch 2.0 Compatibility

### PR DESCRIPTION
**Pull request by atong01**
Test all pytorch versions

Bump allowable torch version requirement

### CODE REVIEW

**Comment by atong01** [comment]
Fixes #200 

Skips a failing test with complex ODEs for torch <1.11.0.

**Comment by atong01** [comment]
Assuming tests pass and @Zymrael approves, would like to push a release `1.0.6` that does not enforce `torch<2.0`

**Comment by Zymrael** [comment]
Looks good, thanks @atong01!

**Comment by atong01** [comment]
Cool. Will release 1.0.6 with this change.

**Pull request merged**
